# NumPy

In [15]:
# 1. Import NumPy

import numpy as np

In [16]:
# 2. Checking NumPy Version

print(np.__version__)

1.26.4


In [17]:
# 3. Creating a NumPy Array

In [10]:
# creating numpy array from list

arr = np.array([2, 4, 6, 8, 10])
print(arr)

[ 2  4  6  8 10]


In [13]:
# checking the data type of arr

arr = np.array([2, 4, 6, 8, 10]) #LIST

print(arr)

print(type(arr))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


In [12]:
# creating numpy array from Tuple

arr = np.array((2, 4, 6, 8, 10)) #TUPLE

print(arr)

[ 2  4  6  8 10]


In [14]:
# checking the data type of arr

arr = np.array((2, 4, 6, 8, 10)) #TUPLE

print(arr)

print(type(arr))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


In [ ]:
# 4. Creating an array with specific dimensions

In [19]:
# 0 Dimension

arr = np.array(3)

print(arr)

3


In [20]:
# 1 Dimension

arr = np.array(['apple', 'banana', 'cherry'])

print(arr)

['apple' 'banana' 'cherry']


In [21]:
# 2 Dimension

arr = np.array([['apple', 'banana', 'cherry'], [1, 2, 3]])

print(arr)

[['apple' 'banana' 'cherry']
 ['1' '2' '3']]


In [22]:
# 3 Dimension

arr = np.array([[['apple', 'banana', 'cherry'], [1, 2, 3]], [['apple', 'banana', 'cherry'], [1, 2, 3]]])

print(arr)

[[['apple' 'banana' 'cherry']
  ['1' '2' '3']]

 [['apple' 'banana' 'cherry']
  ['1' '2' '3']]]


In [23]:
#  5. Check how many dimensions the arrays have

In [24]:
a = np.array(['apple', 'banana', 'cherry'])
b = np.array(3)
c = np.array([['apple', 'banana', 'cherry'], [1, 2, 3]])
d = np.array([[['apple', 'banana', 'cherry'], [1, 2, 3]], [['apple', 'banana', 'cherry'], [1, 2, 3]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

1
0
2
3


In [26]:
# 6. Changing one dimension to another

In [27]:
arr_1 = np.array([2, 4, 6, 8, 10], ndmin=3)

print(arr_1)
print('number of dimension :', arr_1.ndim)
print(arr_1[0])

[[[ 2  4  6  8 10]]]
number of dimension : 3
[[ 2  4  6  8 10]]


In [28]:
# 7. Get the results of the desired elements of the following array

In [29]:
# Get the first element from the following array

arr = np.array([2, 4, 6, 8,10])

print(arr[0])

2


In [30]:
# Get the fourth element from the following array

arr = np.array([2, 4, 6, 8,10])

print(arr[3])

8


In [31]:
# Get the first and third element from the following array

arr = np.array([2, 4, 6, 8,10])

print(arr[0] / arr[2])

0.3333333333333333


In [32]:
# 8. Accessing elements from a specified array.

In [33]:
# Accessing elements using the fourth dimension

fruits = np.array([[[['Apel', 'Jeruk'], ['Pisang', 'Mangga']], [['Anggur', 'Strawberry'], ['Nanas', 'Semangka']]],
                   [[['Durian', 'Jambu'], ['Alpukat', 'Salak']], [['Leci', 'Pepaya'], ['Melon', 'Kiwi']]]])

print(fruits.ndim)
print(fruits[1,0,1,0])

4
Alpukat
