### NUMPY
One of the most frequently used packages in data science and scientific computing is NumPy, as it provides efficient array data structures and a variety of powerful mathematical functions.

First, the code imports NumPy using the statement "import numpy as np". This gives us access to all the functions and objects contained within the NumPy package. Then, we print the version of NumPy being used with "print(np.version)".

In [1]:
# Import NumPy
import numpy as np

In [2]:
# Checking Numpy Version
print(np.__version__)

1.26.4


Next, we create a NumPy array using the np.array() function. We can pass a list [1,2,3,4,5] or a tuple (1,2,3,4,5) as arguments. This generates a one-dimensional array with elements matching the elements of the given list or tuple.

Then, we print the created array with "print(arr)" and print the data type of the array with "print(type(arr))". The result indicates that the created array is a numpy.ndarray object, which is a special data type provided by NumPy to represent multidimensional arrays.

In [3]:
# Creating a NumPy array
list_example = [10, 20, 30, 40, 50]
numpy_array_from_list = np.array(list_example)
print(numpy_array_from_list)

[10 20 30 40 50]


In [4]:
# Use a tuple to create a NumPy array
tuple_example = (60, 70, 80, 90, 100)
numpy_array_from_tuple = np.array(tuple_example)
print(numpy_array_from_tuple)

[ 60  70  80  90 100]


In [5]:
print(type(numpy_array_from_list))
print(type(numpy_array_from_tuple))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


#### DIMENSION
- The dimension in NumPy refers to the number of indices required to refer to an element in the array
##### Dimension in Arrays
- A dimension in arrays is one level of array depth(inested arrays)

In [6]:
# 0-D Arrays
arr = np.array(21)

print(arr)

21


In [7]:
# Create a 1-D array
arr = np.array([20,21,22,23,24,25])
print(arr)

[20 21 22 23 24 25]


In [8]:
# Create a 2-D array containing two arrays
arr = np.array([[20,21,22], [23,24,25], [26,27,28]])
print(arr)

[[20 21 22]
 [23 24 25]
 [26 27 28]]


In [9]:
# Create a 3-D array with two 2-D arrays, both containing two arrays
arr = np.array([[[20,21,22], [23,24,25]], [[20,21,22], [23,24,25]]])
print(arr)

[[[20 21 22]
  [23 24 25]]

 [[20 21 22]
  [23 24 25]]]


In [10]:
# Check how many dimensions the arrays have
a = np.array(21)
b = np.array([20,21,22,23,24,25])
c = np.array([[20,21,22],[23,24,25]])
d = np.array([[[20,21,22], [23,24,25]], [[20,21,22], [23,24,25]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


#### Transforming Dimensions: Converting One Dimension to Another
Transforming one dimension into another dimension in NumPy involves modifying the shape or structure of an array, converting it from one dimension to a different dimension.

In [11]:
# Create an array with 5 dimensions and verify that it has 5 dimensions
fruits = np.array(['Apple', 'Orange', 'Banana', 'Mango', 'Grape'], ndmin=5)

print("Five-dimensional array:")
print(fruits)
print(fruits[0])

Five-dimensional array:
[[[[['Apple' 'Orange' 'Banana' 'Mango' 'Grape']]]]]
[[[['Apple' 'Orange' 'Banana' 'Mango' 'Grape']]]]


In [12]:
# Get the first element from the following array
fruits = np.array(['Apple', 'Orange', 'Banana', 'Mango', 'Grape'])
print(fruits[0])

Apple


In [13]:
# Get the second element from the following array
fruits = np.array(['Apple', 'Orange', 'Banana', 'Mango', 'Grape'])
print(fruits[1])

Orange


In [14]:
# Get third and fourth elements from the following arrays and add them
fruits = np.array(['Apple', 'Orange', 'Banana', 'Mango', 'Grape'])
print(fruits[2] + "and" + fruits[3])

BananaandMango


In [15]:
# Access the element on the 2nd row, 5th column
fruits_2 = np.array([['Apple', 'Orange', 'Banana','Durian', 'Guava'], ['Mango', 'Grape','Avocado','Snake fruit','Lychee']])
print('2nd element on 1st row: ', fruits_2[0,1])

2nd element on 1st row:  Orange


In [16]:
# Access the element on the 2nd row, 5th column
fruits_2 = np.array([['Apple', 'Orange', 'Banana','Durian', 'Guava'], ['Mango', 'Grape','Avocado','Snake fruit','Lychee']])
print('5th element on 2nd row: ', fruits_2[1,4]) #[row,element]

5th element on 2nd row:  Lychee


In [18]:
# Access the third element od the second array of the first array
fruits_2 = np.array([[['Apple', 'Orange', 'Banana',],['Durian','Guava','Watermelon']], [['Mango', 'Grape','Avocado'],['Snake fruit','Lychee','Pineapple']]])
print(fruits_2[1, 0, 2])  #[dim,row,elemen]

Avocado


###### TASK

In [19]:
# Create a four-dimensional array with fruit names
fruit_4d = np.array([[[['Apple', 'Orange'], ['Banana', 'Mango']], [['Grape', 'Strawberry'], ['Pineapple', 'Watermelon']]],
                    [[['Durian', 'Guava'], ['Avocado', 'Snake fruit']], [['Lychee', 'Papaya'], ['Melon', 'Kiwi']]]])

In [20]:
# Display the dimensions, rows, and elements
dimensions = fruit_4d.shape
print("Array dimensions:", dimensions)

Array dimensions: (2, 2, 2, 2)


In [21]:
# Retrieve the element at dimension 1, row 0, and element 0
element = fruit_4d[0, 0, 0, 0]
print("Element at dimension 1, row 0, and element 0:", element)

Element at dimension 1, row 0, and element 0: Apple


In [22]:
fruit_names = np.array([[[['Apple', 'Orange'], ['Banana', 'Mango']],
                  [['Grape', 'Strawberry'], ['Pineapple', 'Watermelon']]],
                  [[['Durian', 'Guava'], ['Avocado', 'Snake fruit']],
                  [['Lychee', 'Papaya'], ['Melon', 'Kiwi']]]])

print(fruit_names[1,0,1,0])

Avocado


- 1 in the first dimension: Selects the second element in the first dimension, which is [[['Durian', 'Guava'], ['Avocado', 'Snake fruit']], [['Lychee', 'Papaya'], ['Melon', 'Kiwi']]].
- 0 in the second dimension: Selects the first row in the second dimension, which is [['Durian', 'Guava'], ['Avocado', 'Snake fruit']].
- 1 in the third dimension: Selects the second element in that row, which is ['Avocado', 'Snake fruit'].
- 0 in the fourth dimension: Selects the first element in that row, which is 'Avocado'.